language: python
sudo: false

branches:
    only:
      - master
python:
  - 3.6
  - 3.5
  - 2.7

install:
  - pip install . flake8 pytest-flake8 flake8-docstrings flake8-import-order

script:
  - pytest --flake8
